language: node_js
node_js:
  - "6"
sudo: false
install:
  - npm install
script:
  - npm test
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
